export const GET_MODELS = 'GET_MODELS';
export const ADD_MODEL = 'ADD_MODEL';
export const DELETE_MODEL = 'DELETE_MODEL';
export const MODELS_LOADING = 'MODELS_LOADING';
export const ADD_MODEL_FIELD = 'ADD_MODEL_FIELD';

export const GET_MODELTYPES = 'GET_MODELTYPES';
export const ADD_MODELTYPE = 'ADD_MODELTYPE';
export const DELETE_MODELTYPE = 'DELETE_MODELTYPE';
export const MODELTYPES_LOADING = 'MODELTYPES_LOADING';

export const GET_INSTANCES = 'GET_INSTANCES';
export const DELETE_INSTANCE = 'DELETE_INSTANCE';
export const INSTANCES_LOADING = 'INSTANCES_LOADING';
export const ADD_INSTANCE_ITEM = 'ADD_INSTANCE_ITEM';
export const ADD_INSTANCE = 'ADD_INSTANCE';