export const GET_MODELS = 'GET_MODELS';
export const ADD_MODEL = 'ADD_MODEL';
export const DELETE_MODEL = 'DELETE_MODEL';
export const MODELS_LOADING = 'MODELS_LOADING';
export const ADD_MODEL_FIELD = 'ADD_MODEL_FIELD';
export const BUILD_MODEL = 'BUILD_MODEL';

export const GET_MODELTYPES = 'GET_MODELTYPES';
export const ADD_MODELTYPE = 'ADD_MODELTYPE';
export const DELETE_MODELTYPE = 'DELETE_MODELTYPE';
export const MODELTYPES_LOADING = 'MODELTYPES_LOADING';